from vehicles import base, passenger_car, ferry_boat, parts, vehicles_exceptions

print('Demonstration od PassengerCar class:')
car = passenger_car.PassengerCar('Opel', 'Astra')
car.make_sound()
print("car.fuel: ", car.fuel)
car.add_fuel(-600)
print("car.fuel: ", car.fuel)
car.add_fuel(650)
print("car.fuel: ", car.fuel)
car.ride(500)
car.set_engine(parts.sport_engine)
print(car.engine)
car.add_fuel(750)
car.ride(500)

print('\nDemonstration od FerryBoat class:')
ship = ferry_boat.FerryBoat('Syma', 'Black Stealth', 'Queen')
ship.make_sound()
print("ship.fuel: ", ship.fuel)
ship.add_fuel(-600)
print("ship.fuel: ", ship.fuel)
ship.add_fuel(550)
print("ship.fuel: ", ship.fuel)
ship.sail(500)
ship.bring_cargo(5000)
print(f"ship.cargo: {ship.cargo}, consumption index: {ship._cargo_consumption_index}")
ship.offload()
print(f"ship.cargo: {ship.cargo}, consumption index: {ship._cargo_consumption_index}")