"""add column deleted

Revision ID: cb606e21ba96
Revises: 935b8da1028c
Create Date: 2020-12-03 01:03:10.940857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb606e21ba96'
down_revision = '935b8da1028c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted')
    # ### end Alembic commands ###
